### ISSUE TITLE
Toggle Private Session

### ISSUE THREAD

**Issue by marclundgren** [hnarayanan/shpotify#101]
hi @hnarayanan,

Could the tool potentially support toggling the `Private Session`?

![screen shot 2018-06-11 at 11 52 35 am](https://user-images.githubusercontent.com/1154834/41251180-faf501d0-6d6d-11e8-91ff-16bad3e33890.png)

**Comment by hnarayanan** [comment]
It’s possible but I don’t know for sure. If you can find an AppleScript event that corresponds to this, e.g. “tell application to ‘turn on private mode’”, then it’s easy to add to the script.

**Comment by marclundgren** [comment]
I just opened an issue for spotify to support this via web API

https://github.com/spotify/web-api/issues/913

**Comment by marclundgren** [comment]
> osascript -e 'tell application "Spotify" to session as string'

@hnarayanan how can I find a list of variables that osascript can access on an application? any guides or references would be helpful. 

resources I've tried:
https://ss64.com/osx/osascript.html

**Comment by dmofot** [comment]
@marclundgren You should be able to see which variables can be passed in the sdef file.  Depends where Spotify is installed, but mine is located in `/Applications/Spotify.app/Contents/Resources/Spotify.sdef`

**Comment by marclundgren** [comment]
looks like there's no access to the private session in Spotify.sdef :(

**Comment by hnarayanan** [comment]
Thank you for doing the research though, and thanks @dmofot. Unfortunately this issue needs to be closed. Please reopen this is the situation changes with how we can control Spotify.
