### ISSUE TITLE
Running spotify command generates permissions related error output

### ISSUE THREAD

**Issue by philipdowner** [hnarayanan/shpotify#102]
Running any `spotify` command in my terminal (iTerm or Terminal) executes the command but also outputs the following permissions error:

```bash
osascript[62109:4956741] kCFURLVolumeIsAutomountedKey missing for file:///Volumes/casper/: Error Domain=NSCocoaErrorDomain Code=257 "The file “casper” couldn’t be opened because you don’t have permission to view it." UserInfo={NSURL=file:///Volumes/casper/, NSFilePath=/Volumes/casper, NSUnderlyingError=0x7fe0316026e0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
```

**Comment by dmofot** [comment]
@philipdowner are you still having this issue?  This looks like something private has been loaded into `/Volumes` and probably has nothing to do with shpotify.  Could you try running `osascript -e 'tell application "Finder" to activate'` in your terminal and see if you get the same error or if the Finder is activated.

**Comment by hnarayanan** [comment]
Sorry, this indeed has nothing to do with this project and more to do with the permissions of your existing setup.
