### ISSUE TITLE
list search functionality returns no results consistently

### ISSUE THREAD

**Issue by johnalanwoods** [hnarayanan/shpotify#110]
List functionality was working perfectly however recently it's stopped working.

Confirmed API is set up correctly in the .cfg.

**Comment by johnalanwoods** [comment]
any ideas guys?

Spotify play list rap/rock/whatever used to work, not it's always returning no results...

**Comment by dmofot** [comment]
@johnalanwoods I think this is at the whim of what Spotify returns.  A couple weeks ago I tried `spotify play list metallica` and it didn't work with any of the recent versions of shpotify.  Just tried it again today and it's working fine.  Give it a shot and let us know if it works.

**Comment by chrismaltais** [comment]
Hey guys,

Just found this repo, installed, and configured the tool but I'm getting the same error. See below.

![Screen Shot 2019-03-22 at 9 55 49 PM](https://user-images.githubusercontent.com/17098959/54860209-62334c80-4ced-11e9-9621-1279041eefc4.png)

Let me know if others can replicate.

**Comment by hnarayanan** [comment]
I can confirm this.
