### ISSUE TITLE
Feature Request: Ability to print song title/artist

### ISSUE THREAD

**Issue by jsatk** [hnarayanan/shpotify#113]
I'd love to be able to either

1. Print the status to JSON so it can be parsed
2. Allow spotify status to accept flags or further params to just get the song or artist.

**Comment by hnarayanan** [comment]
This is now available, thanks to: https://github.com/hnarayanan/shpotify/pull/78

**Comment by jsatk** [comment]
Yay!

**Comment by jsatk** [comment]
@hnarayanan any idea when this will be released via homebrew?

**Comment by hnarayanan** [comment]
No. I'd like to merge a handful more of the existing PRs, stabilise the script, then make a GitHub release. This could take anywhere from minutes to weeks. :)

Then someone in the community has to package the new release in Homebrew.
