### ISSUE TITLE
spotify status watch mode 

### ISSUE THREAD

**Issue by rupertdev** [hnarayanan/shpotify#115]
Hey there, love the tool!

One feature that I would love to see is an updating spotify status command that I can keep in a small section of my screen. 

Essentially what `watch spotify -n 1` outputs, without any weird characters, updating until i ctrl-c. 

Thanks!

**Comment by dmofot** [comment]
I haven't used it on OSX, but `watch` can be installed using homebrew.  Alternatively, you could try something like `while :; do echo "$(clear;spotify status)"; sleep 2; done` which will continually run the `spotify status` command until you CTRL+C.  Quick gif to below to show the song position updating...

![watch](https://user-images.githubusercontent.com/5605132/76106125-3b286600-5fa4-11ea-8d17-d059b5651c90.gif)

Would that be sufficient or do you envision this being something built into the script itself?

**Comment by rupertdev** [comment]
It would be neat to have it built in, but this will work for us more technical users.
