### ISSUE TITLE
${HOME}/.shpotify.cfg no diea what to do

### ISSUE THREAD

**Issue by fredyonge** [hnarayanan/shpotify#125]
Sorry this is not an issue, but I dont know what to do at the step : ${HOME}/.shpotify.cfg

Do I go into the terminal, if so, I went into my home directory but couldn't use the that. Could you help me?

**Comment by dmofot** [comment]
`${HOME}/.shpotify.cfg` will be created for you if you don't already have one.  In your terminal, if you simply run `spotify`, it will print out the tools current usage and setup.  You'll see a section at the bottom called *Connecting to Spotify's API:*. Simply follow the directions (copied below) to grab a CLIENT_ID and CLIENT_SECRET from Spotify.  Once you have those values, edit your `${HOME}/.shpotify.cfg` to include your new/updated values.  How you edit the file is up to you (nano, vim, VSCode, etc.), but if you need a GUI, something like `$ open ~/.shpotify.cfg -a textedit` should open the file for editing.

> This command line application needs to connect to Spotify's API in order to
>   find music by name. It is very likely you want this feature!
> 
>   To get this to work, you need to sign up (or in) and create an 'Application' at:
>   https://developer.spotify.com/my-applications/#!/applications/create
> 
>   Once you've created an application, find the 'Client ID' and 'Client Secret'
>   values, and enter them into your shpotify config file at '${HOME}/.shpotify.cfg'
> 
>   Be sure to quote your values and don't add any extra spaces!
>   When done, it should look like this (but with your own values):
>   CLIENT_ID="abc01de2fghijk345lmnop"
>   CLIENT_SECRET="qr6stu789vwxyz"

**Comment by dmofot** [comment]
Going to close this issue.  Feel free to respond if you haven't gotten setup sorted.
