### ISSUE TITLE
Shpotify some times doesn't show track and artist

### ISSUE THREAD

**Issue by henrik242** [hnarayanan/shpotify#128]
```
🐤 spotify status 
Spotify is currently playing.
Artist: Brotherhood
Album: Two Worlds And In Between 2013-2017
Track: Heaven and The End 
Position: 0:53 / 3:39
🐤 spotify prev
Going to previous track.
Spotify is currently playing.
Artist: 
Album: Metropakt
Track:  
Position: 0:00 / 2:41
🐤 spotify status 
Spotify is currently playing.
Artist: 
Album: Metropakt
Track:  
Position: 0:04 / 2:41
🐤 spotify next
Going to next track.
Spotify is currently playing.
Artist: 
Album: Two Worlds And In Between 2013-2017
Track:  
Position: 0:00 / 3:39
🐤 spotify status 
Spotify is currently playing.
Artist: 
Album: Two Worlds And In Between 2013-2017
Track:  
Position: 0:04 / 3:39
```

Shpotify 2.1 from Homebrew on macOS 10.15.4

**Comment by hnarayanan** [comment]
Do you really have a chick for your console prompt? 😸

**Comment by henrik242** [comment]
It's my easter themed prompt.  Guess it's time to change it again :)

**Comment by siralmat** [comment]
Hello! I stumbled across this thread while troubleshooting the same problem in my own Spotify script. 

This is a newly introduced bug in Spotify: it appears that when you manually change the current track (by moving to the next/previous track, selecting a new track, or pausing/unpausing), it updates the current track properties _except for_ the title and artist/album artist, which are blanked out. They only update correctly when the player moves to a new track on its own, after the current track ends. A [few other users](https://community.spotify.com/t5/Desktop-Mac/You-broke-AppleScript-Again/m-p/4937134) have reported the bug on the Spotify support forums so hopefully a fix will be out soon...

Anyway, I just wanted to share this to hopefully save you some debugging headaches. 🙂Awesome project, btw!

**Comment by hnarayanan** [comment]
Yay. We just wait then.

**Comment by hnarayanan** [comment]
Closing because this is an issue with the Spotify app.
