### ISSUE TITLE
Bash only or zsh as well? 

### ISSUE THREAD

**Issue by davidem** [hnarayanan/shpotify#136]
I've got a question: the README states this is a bash script, so I've been coding with some nice _bashism's_ but I see som zsh fans using Shpotify as well: How well is the compatibility between bash and zsh? What are the things I need to take into account? 

:)

**Comment by hnarayanan** [comment]
It is already used by a ton of oh-my-zsh users so I don't think this needs to explicitly be stated.

It is a bash script because it's ostensibly written in bash.

**Comment by davidem** [comment]
I was more looking for programmatical differences between bash and zsh, so I can take those into account. 

This site got me covered: https://apple.stackexchange.com/questions/361870/what-are-the-practical-differences-between-bash-and-zsh

**Comment by hnarayanan** [comment]
Please slow down.

**Comment by davidem** [comment]
haha, sorry about that. I'm away this weekend, so that will slow me down a bit :)

**Comment by hnarayanan** [comment]
As happens a lot, I am going through a lot of personal stuff right now so I'll review all your contributions in time.

**Comment by davidem** [comment]
So I have read, and please take care :) Maybe a silly question, but are you the sole maintainer? 

I have 3,5 things I want to implement tonight after which I'll take a break for a few days: 
- like albums / tracks (tracks-part is done, next is albums)
- list track/album info. To be used with 'like albums/tracks', but also as single requests
- check if track/album is liked. To be used with 'like albums/tracks, perhaps also as a single request. 
- queue tracks (although it is not possible to view the queue via an API)

I do hope you like my contributions and I'm looking forward to see your requests/remarks/suggestions.

As said: take care!

Ciao,

David
