### ISSUE TITLE
Support Spotify v1.0.1.1060

### ISSUE THREAD

**Issue by yoeran** [hnarayanan/shpotify#14]
Shpotify worked like a charm with Spotify 0.9.15.27, but gives me execution errors after I updated Spotify to version v1.0.1 today.

I'm getting the following errors
```
$ ./spotify play
Playing Spotify.
30:34: execution error: The variable play is not defined. (-2753)
```

```
$ ./spotify pause
Pausing Spotify.
30:35: execution error: The variable pause is not defined. (-2753)
```

They probably renamed some actions in Spotify?

**Comment by hnarayanan** [comment]
Oh noes :disappointed:.

Yes, they probably changed the Applescript interface. I will try to find and read some documentation and fix this, eventually. If anyone wants to jump ahead and try this, patches will be most welcome. :heart:

**Comment by yoeran** [comment]
I've never really worked with Applescript before, how do you find out about the Applescript commands?
With that info I can at least give it a try to make a patch.

**Comment by hnarayanan** [comment]
I thought it would be a quick Google search but I'm not able to find anything handy. Will be on the lookout for some official-seeming docs and report back if I stumble upon anything.

[This Stack Exchange thread](http://apple.stackexchange.com/questions/46521/how-do-i-find-out-the-applescript-commands-available-for-a-particular-app) might be helpful.

**Comment by sbaxter** [comment]
https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/New-Mac-Update-AppleScript-support-removed/m-p/1044011#M112587

**Comment by sbaxter** [comment]
Update your `Spotify.app/Contents/Info.plist` and restart spotify:
```
  <key>NSAppleScriptEnabled</key>
  <true/>
  <key>OSAScriptingDefinition</key>
  <string>applescript/Spotify.sdef</string>
```

**Comment by hnarayanan** [comment]
Thank you. :+1:

Or hopefully this is temporary and we'll need to do nothing once this regression is fixed in subsequent releases of Spotify.

**Comment by sbaxter** [comment]
Yes, I assume a permanent fix is on the way :)

**Comment by skamsie** [comment]
After updating the 'Info.plist' some of the commands are still not working for me:

    play album [album name]         # Finds an album by name and plays it.
    play artist [artist name]       # Finds an artist by name and plays it.
    play list [playlist name]    

Any ideas how to fix it?

Thanks

**Comment by thepuzzlemaster** [comment]
For what it's worth, Spotify has marked the issue as 'watch this space' meaning it will be resolved in a future update. I have not yet found a workaround for the play-track issue, which the above three commands use.

**Comment by hnarayanan** [comment]
Yay!

**Comment by thepuzzlemaster** [comment]
They claim the latest release fixes the issue. I ended up downgrading and preventing upgrades, so I haven't tested myself though: https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/New-Mac-Update-AppleScript-support-removed/td-p/995843/page/2

**Comment by thepuzzlemaster** [comment]
Installed version 1.0.301 and it fixed the issue on my end. I think you should be able to close this issue @yoeran.

**Comment by hnarayanan** [comment]
Again. Yay :+1:.
