### ISSUE TITLE
Issue with homebrew package?

### ISSUE THREAD

**Issue by erikc96** [hnarayanan/shpotify#141]
Hi,

I went to try out this interesting package earlier, using 'brew install shpotify,' and unfortunately found that the installation didn't work quite as expected. I get a 'command not found' error. I see that it's been installed into '/usr/local/Cellar/shpotify' just fine, it's just not executable? Would appreciate any help getting this app running.

Thank you,
erik

**Comment by hnarayanan** [comment]
I don’t use Homebrew, but if you know how to, you can simply clone this repository and set it up manually.

Otherwise, you need to dig deeper into how Homebrew sets it up.

**Comment by erikc96** [comment]
Okay! That's just as fine for me!
