### ISSUE TITLE
Shuffle/ Repeat State?

### ISSUE THREAD

**Issue by moshed** [hnarayanan/shpotify#148]
is there a way to return the Shuffle and/or repeat state?

**Comment by davidem** [comment]
There's a hidden feature, "info", which shows the current shuffle state (2nd from the bottom):

> ./spotify info
> 
> Artist:         Nirvana
> Track:          In Bloom - Nevermind Version
> Album Artist:   Nirvana
> Album:          Nevermind (Deluxe Edition)
> Seconds:        255,08
> Seconds played: 11,996999740601
> Duration:       4min 15s
> Now at:         0min 11s
> Played Count:   0
> Track Number:   2
> Popularity:     65
> Id:             spotify:track:0eeEzvw5Etwv6tyz2PyE6L
> Spotify URL:    spotify:track:0eeEzvw5Etwv6tyz2PyE6L
> Artwork:        https://i.scdn.co/image/ab67616d0000b27328a90d00a2819504364880e4
> Player:         playing
> Volume:         54
> Shuffle:        false
> Repeating:      false

**Comment by moshed** [comment]
ohhh lovely! thanks!

**Comment by hnarayanan** [comment]
Yay.
