### ISSUE TITLE
Configurable volume up/down percentage appears to have been reverted

### ISSUE THREAD

**Issue by willhaslett** [hnarayanan/shpotify#149]
I suggested this feature and implemented here: https://github.com/hnarayanan/shpotify/issues/129. It was merged in, here: https://github.com/hnarayanan/shpotify/pull/130

Upon a new brew install today, it appears that that change has been reverted. Can we have it back? Same logic as the original issue: 10% is too coarse an adjustment for me. I suspect that it's too coarse for anyone listening to through a system that has audiophile-type dynamic range.

If there's a good reason it's gone, no worries, I'll just make "10" "5".

**Comment by hnarayanan** [comment]
There is no good reason. It is simply an oversight.

**Comment by dmofot** [comment]
I don’t think it was reverted, there just hasn’t been another tagged version which means there hasn’t been another homebrew release since before that change was merged to master.  Unless you’re using brew to install master...

**Comment by willhaslett** [comment]
Ah, I see. Thank you.
