### ISSUE TITLE
Shpotify not detecting spotify build from source

### ISSUE THREAD

**Issue by hafizdkren** [hnarayanan/shpotify#153]
So I was installing EndeavourOS and wanna to configure my zsh, everything was set OK and also adding application API key on it.
But, every times I try to testing it by `spotify status` it say 
> The Spotify application must be installed.

So, I was confused. If this just me, please send me a how to so I can configure it more. But if this is a bug then I'll wait for next commit.

Thanks

**Comment by hnarayanan** [comment]
Sorry, but this is a Mac-only application.

**Comment by hafizdkren** [comment]
Oh, I see. sorry for trouble
