### ISSUE TITLE
support for other distributions other than Mac

### ISSUE THREAD

**Issue by cevhyruz** [hnarayanan/shpotify#155]
Hello, thank you for this wonderful project. I've followed all the directions on readme. I have also installed the spotify-client, however I'm still getting a "The Spotify Application must be installed."  upon checking the codebase I've found out It's looking at the wrong directory `Applications/` which i assume a Mac thing.

**Comment by hnarayanan** [comment]
Hi John! Thank you for writing but unfortunately this is a Mac only project.

I will close this issue, but please do link below a good alternative app for Linux if you find it. I’m sure it would help the next person searching for this.
