### ISSUE TITLE
Enable Sponsoring?

### ISSUE THREAD

**Issue by thomasmalley** [hnarayanan/shpotify#157]
Hey, I am getting a lot of value from you app. Have you been thinking about enabling GitHubs Sponsoring feature for this repo?

**Comment by hnarayanan** [comment]
Sounds really wonderful. Could you point me to where I could get started?

**Comment by thomasmalley** [comment]
Sure! Here you go: https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-user-account 

Currently it's available for bank accounts in 36 regions. [Here](https://github.com/sponsors#regions) you'll find an overview. I hope it works for you 🤞🏼 

PS: If it does, I'll try to become your first sponsor off course 🚀

**Comment by hnarayanan** [comment]
Thank you so much for the kick that I needed to enable this. I have turned on the sponsorship option. 🙏

**Comment by thomasmalley** [comment]
Kept my promise to you :) Thank you for your awesome work & all the best for your family!

**Comment by hnarayanan** [comment]
Amazing! Thank you for being my first sponsor.

**Comment by hnarayanan** [comment]
Also, could you explain to me (when you get the time) how you feel you get a lot of value out of the app?

**Comment by hnarayanan** [comment]
Amazing, thank you for sharing. I suffer from CTS too and just don’t/can’t do certain classes of things. I should look for alternate interfaces ☺️
