### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by bfontaine** [hnarayanan/shpotify#21]
Hello,

Would you mind versionning the script and tagging it on the git repo? You can start at, say, `0.1.0` or `1.0.0` then increment when you make some changes. Use git tags to get [releases](https://github.com/hnarayanan/shpotify/releases) on GitHub.

I’d like to submit a PR to [Homebrew](https://github.com/Homebrew/homebrew) to get a formula for `shpotify` but they disallow formulae without versions in the main repo.

Thanks!

**Comment by hnarayanan** [comment]
Sure, let's arbitrarily start this project at 1.0.0. :)

**Comment by bfontaine** [comment]
Thanks, just submitted [a PR to Homebrew](https://github.com/Homebrew/homebrew/pull/38746).

**Comment by bfontaine** [comment]
It has been merged, Homebrew users can now install shpotify with `brew install shpotify` :smile:

**Comment by hnarayanan** [comment]
Excellent, thanks both for the patch to homebrew and for informing us here.
