### ISSUE TITLE
Please make it possible to play a spotify URI or URL

### ISSUE THREAD

**Issue by elijahchancey** [hnarayanan/shpotify#30]
This would also solve issue #26 

Thanks!

**Comment by hnarayanan** [comment]
There exists a pull request that might resolve this. Could you test it and report if it satisfies your needs?

https://github.com/hnarayanan/shpotify/pull/27

**Comment by hnarayanan** [comment]
@elijahchancey: Please let me know if https://github.com/hnarayanan/shpotify/pull/48 is heading in the direction you want.
