### ISSUE TITLE
choose playlist

### ISSUE THREAD

**Issue by tnguyen14** [hnarayanan/shpotify#4]
Can we add the option to list and select a playlist to play?

**Comment by thepuzzlemaster** [comment]
Not quite list and play, but it does allow for some playlist interactivity. Could be a good starting point for what you're looking for:
https://github.com/hnarayanan/shpotify/pull/5

**Comment by hnarayanan** [comment]
@thepuzzlemaster: How does my hypothetical command line interface look?

https://github.com/hnarayanan/shpotify/blob/master/README.md

Please suggest any changes if you have any. When you're happy with this, we can easily expand your implementation to meet the interface. Also, if you'd like, you're free to add yourself to the list of contributors in the script and README file.

**Comment by thepuzzlemaster** [comment]
Hmmm. Yeah, I think that looks pretty good. I'll make the necessary changes for the searching stuff.

I'm also going to have searches for playlists return 10 results and choose one at random so the same search string may return different results. 

Thanks!

**Comment by hnarayanan** [comment]
This feature request been implemented in a pretty solid fashion. Please check out the current master branch and many thanks to @thepuzzlemaster!
