### ISSUE TITLE
Times/Durations Incorrect

### ISSUE THREAD

**Issue by dmofot** [hnarayanan/shpotify#42]
It looks like `spotify info` is outputting the wrong **Seconds** and **Duration**.  In addition, the `spotify status` command has **Position** displayed in decimal format (mm.mm) rather than Minutes:Seconds (mm:ss).  Here's an example output, song duration is actually 3:41 (3 minutes 41 seconds):
```
$ spotify info && spotify status

Artist:         Das EFX
Track:          They Want EFX
Album Artist:   Das EFX
Album:          Dead Serious
Seconds:        221400
Seconds played: 85.104
Duration:       3690min 0s
Now at:         1min 25s
Played Count:   0
Track Number:   3
Popularity:     44
Id:             spotify:track:3HCzj965m8Fz2E8wZkir6q
Spotify URL:    spotify:track:3HCzj965m8Fz2E8wZkir6q
Artwork:        missing value
Player:         playing
Volume:         43
Shuffle:        true
Repeating:      false
Spotify is currently playing.
Artist: Das EFX
Album: Dead Serious
Track: They Want EFX
Position: 1.42 / 3.69
```
`spotify info` issues: So **Seconds** should be *221.400* and not *221400*.  It's currently missing the decimal, although everything after the decimal can probably be dropped.  **Duration** should be *3:41*, which is the mm:ss.  It's currently showing the decimal, but the decimal is missing - *3690min 0s* - ((3 minutes x 60 seconds) + 41) = 221 seconds / 60 seconds = *3.683min*.

`spotify status` issues: **Position** is currently displaying minutes in decimal *1.42 / 3.69*, which is the **Now at** of *1min 25s* in decimal ((1 minute x 60 seconds) + 25 seconds) = 85 / 60 seconds = *1.416* and the correct **Duration** shown above, *3.69*.

I've never written any AppleScript before, but I'll take a look.  My initial guess is the **Seconds** is actually miliseconds.

**Comment by hnarayanan** [comment]
Please take a look!

**Comment by ericmarkmartin** [comment]
I came up with this: https://github.com/hnarayanan/shpotify/pull/43
