### ISSUE TITLE
Version 1.2

### ISSUE THREAD

**Issue by tpritc** [hnarayanan/shpotify#53]
@hnarayanan I think with all of the recent improvements and features, it's time for a v1.2 release (inc. sending it out via Homebrew).

If we create a new release, could @bfontaine update the Homebrew stuff?

**Comment by ericmarkmartin** [comment]
Agreed. I was about to post the same thing. I can also make the necessary homebrew pages as long as there is a release on github.

**Comment by hnarayanan** [comment]
Sure, once @ericmarkmartin can help confirm that #52 is not a bug.

**Comment by hnarayanan** [comment]
I've now tagged a 1.2.0 release. I don't think anything needs to be done for homebrew, but if it needs to be, someone else please look into it as I don't know anything about that. 😄

**Comment by dmofot** [comment]
I just updated the formula in [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) with pull request [#4983](https://github.com/Homebrew/homebrew-core/pull/4983) and it's been merged.

**Comment by ericmarkmartin** [comment]
Was just about to do that. Thanks @dmofot.

**Comment by hnarayanan** [comment]
Thank you!

**Comment by ubuntudroid** [comment]
@dmofot Thanks for updating the homebrew formula for me! 👍  I was without internet yesterday, and just about to do it when I saw it already done. 😄
