### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by archcorsair** [hnarayanan/shpotify#70]
Love this little tool, use it at work all the time. At home I work on linux (Ubuntu 16.10).
Would be great to be able to use it at home too :smiley: 

When attempted to run on Linux:
```
[0305/145225:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
[0305/145225:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
```
Spotify restarts when I attempt to run the `spotify` command

**Comment by tpritc** [comment]
This makes heavy use of the Applescript support in the macOS client of Spotify, so unless I'm mistaken, Linux support is _really_ unlikely.

**Comment by dmofot** [comment]
@archcorsair similar Linux clients already exist.  You might have a look at [sp](https://gist.github.com/wandernauta/6800547).

**Comment by hnarayanan** [comment]
Exactly. 😀 I am closing this because it is well outside the scope of what this project tries to be, but please do try alternatives as @dmofot suggests.
