### ISSUE TITLE
toggle repeat does not handle "repeat single track" mode

### ISSUE THREAD

**Issue by bjornrud** [hnarayanan/shpotify#72]
Thanks for this package!!!  Happened upon this:

**Steps to reproduce** 
 - Use the spotify client to set repeat to single track mode (the repeat w/ a `1` badge)
 - Issue `spotify toggle repeat` command. 
 - Regardless of command output, the spotify client's repeat mode is _still_ set to single track, and will incorrectly report `false`

**Expected Behaviors**
 - `toggle repeat` when spotify is in a repeat single track mode, will set the repeat mode to `false` in the spotify client.
 - `toggle repeat` moves between the three statuses of `false`, `repeat single track`, and `repeat playlist`.  This is just one possible implementation.  
    - Other possible combinations of suggestions include: renaming `toggle repeat` to `toggle repeat-queue` would reflect the current behavior.  Adding `toggle track-repeat` command.

**Comment by hnarayanan** [comment]
Thanks for this! I think I understand what you're getting at, but I am not super clear. Would you like to try submitting a pull request so I can see the behaviour you expect in code?

**Comment by bjornrud** [comment]
@hnarayanan Would you be amenable to breaking the expected behavior into a different feature request?  I would leave the fact that `toggle` has no effect whatsoever in single-track mode as a separate bug issue.  I want to PR your work, but can't promise anything as I have the most basic understanding of `bash`
