### ISSUE TITLE
Package does not list Spotify as a dependency

### ISSUE THREAD

**Issue by aaronrudkin** [hnarayanan/shpotify#73]
This might seem obvious, but nothing on the shpotify main page lists Spotify as a dependency. I think I'm probably not the only person to assume that shpotify was a command-line spotify client, rather than a command-line dispatcher for the official Spotify application. ("Interface" in the project description is ambiguous as to which meaning of the word it refers to)

In addition, once installed, the error messages are not really kind or user friendly:
``` 
aaron@mb:~$ spotify play The Boy in the Bubble
30:38: execution error: Can’t get application "Spotify". (-1728)
Searching tracks for: The Boy in the Bubble
Playing (The Boy in the Bubble Search) -> Spotify URI: spotify:track:00IrSynHsun7DpDrLkRIjM
30:40: syntax error: A identifier can’t go after this identifier. (-2740)
```

One would think that the error message would a) note that the issue is that Spotify is not installed, and b) not do the search once it fails to find the application.

**Comment by hnarayanan** [comment]
(I am not sure why I missed this earlier.)

This is a good idea. Would you like to submit a patch?

**Comment by heroichornet** [comment]
Is there a command line client out there somewhere?

**Comment by jackchouchani** [comment]
I don't really see the point of having the shpotify config file. I tried signing out of spotify, to play a song on my terminal and it was not working. So it just proves that shpotify relies on the Spotify client. I think I'm not the only one who got misinformed. The Client ID and Client secret were not used.

**Comment by jackchouchani** [comment]
Oh and I forgot to mention that it works the same regardless of the client ID and client secret.
