### ISSUE TITLE
Random search seems to do the wrong thing?

### ISSUE THREAD

**Issue by hnarayanan** [hnarayanan/shpotify#8]
@thepuzzlemaster: I am not sure that randomly picking one of the returning search results is the best behaviour since the returning results are already sorted in some way (perhaps popularity?) the first result seemed to work for me.

e.g. 
````
search query          what i expect                       searchtrack behaviour               current behaviour
amazing               amazing by kanye west               amazing by kanye west               all you need is a spark by danny saucedo
blood on the leaves   blood on the leaves by kanye west   blood on the leaves by kanye west   only one by kanye west
````

Picked one multi-word and one single word song name as an example.

If you agree that this behaviour should be changed, do you want me to do it or should I?

**Comment by thepuzzlemaster** [comment]
Hmmm. The only search that chooses at random is playlist. All of the others pick the first result, which I do believe is sorted by how closely it matches the query.

Let me investigate a little bit.

**Comment by thepuzzlemaster** [comment]
So I think the issue is I'm now using the search api (https://api.spotify.com/v1/search) instead of what I was using previously: (ws.spotify.com/search/1/track)

The same query returns results in a different order for the two searches. Although amazing should at least return the track 'amazing' by Danny Saucedo instead of the other one you're seeing.

Looking into it a little more.

**Comment by hnarayanan** [comment]
In both cases (Kanye West and Danny Saucedo), the songs being returned are the most popular song by the artist, at least on my U.K.-based account.

**Comment by hnarayanan** [comment]
So it is somehow going from Amazing to Amazing by Danny Saucedo (not problematic) but then to their most popular song.

In the other case it's going from Blood on the Leaves to Kanye West (so far so good) to Only One.

**Comment by thepuzzlemaster** [comment]
I have found the issue. The previous search method was using a different API endpoint, which locked the results to the US, whereas the new one is not. I can lock it down to the us, which then returns Kanye West as the first result, but I'm not sure that's what we want to do.

See here:
https://developer.spotify.com/web-api/console/get-search-item/#complete

fill in 'amazing' as the query, 'track' as the type, leave market blank, `1` as the limit and `0` as the offset.

Then run the query again with the market as 'US'.

**Comment by thepuzzlemaster** [comment]
Previously, I was using this endpoint:
https://ws.spotify.com/search/1/track?q=amazing

**Comment by hnarayanan** [comment]
Can you try passing the `type=foo` business as part of the GET query instead of `-d`? I think that's the problem.

**Comment by hnarayanan** [comment]
The problem is how you're passing the GET query parameters now I think. I don't think `-d` is doing what you expect here, hence the odd result, and it's always returning the artist, which in turn points to their most popular song.

**Comment by thepuzzlemaster** [comment]
Okay, let me try changing those.

**Comment by hnarayanan** [comment]
And yes, if needed, hardcode the zone to the U.S. I'd rather listen to Kanye West than Daniel Saucedo! :)

**Comment by thepuzzlemaster** [comment]
Ugh. Typo in the grep for track search (line 131). I was searching for an artist uri instead of track.

That does explain the results.

**Comment by hnarayanan** [comment]
Before you commit any fixes, be sure to pull the repository. I've been mucking around with it a lot in the last half an hour.

**Comment by thepuzzlemaster** [comment]
Okay, that was the issue. However the track 'amazing' by Danny Saucedo still does return as the #1 result.

You can search for `amazing kanye` which does return amazing by kanye.

Locking the results to the US market may have implications on other people using this.

What do you think? I think I would lean towards leaving the market open. Although I'm also not sure what the implications are for trying to play a song that is not in your market. Going to try that out real quick.

**Comment by thepuzzlemaster** [comment]
It looks like trying to play music from outside your market works correctly. So I am inclined to leave all markets open. And if the search for your track by name is not returning what you want, add another work to make it more specific.

**Comment by hnarayanan** [comment]
Agreed. Even though I think the default search results are stupid. :)

Excellent detective work and thanks for the fix.

**Comment by thepuzzlemaster** [comment]
Thanks for the help. Tracking down what was actually happening (playing the most popular song by the artist) was key in finding the actual cause. I think Danny Saucedo is really to blame here :+1:

**Comment by hnarayanan** [comment]
So do I!
