### ISSUE TITLE
Commands involving search don't seem to work on zsh

### ISSUE THREAD

**Issue by hnarayanan** [hnarayanan/shpotify#84]
The details of this were slowly beginning to take shape in the discussion on an earlier issue: https://github.com/hnarayanan/shpotify/issues/76#issuecomment-342271420

**Comment by hnarayanan** [comment]
And in the previous issue (linked above), I mentioned that it worked for sometime and then stopped working. I thought it had something to do with time (like 30min--1 hour), but it might actually have something to do with me closing and opening my shell window. This is why I think it has something to do with how the config file is sourced.

cc: @g-bon, @nevinvalsaraj, @jillmolloy

**Comment by hnarayanan** [comment]
This is really confusing and interesting.

It turns out that I not only use `zsh` but a collection of scripts for it called `oh-my-zsh` that adds some useful functionality on top. Anyway, someone (@mahi97) has copied an old version of this script into this project wholesale: https://github.com/robbyrussell/oh-my-zsh/blame/d874c73f19d8430f4dc32756fff0bf2f6a804d87/plugins/osx/osx.plugin.zsh

Which is why it has been working for me sometimes (when I referred to the correct script), and not sometimes. Similarly for Jill I presume.

**Comment by hnarayanan** [comment]
https://github.com/robbyrussell/oh-my-zsh/pull/5356#issuecomment-344048908

**Comment by g-bon** [comment]
That's really interesting, would you need to update oh-my-zsh every time there is an update here or you can just remove from there so that shpotify installed with homebrew is picked automatically?

**Comment by hnarayanan** [comment]
I am not sure, and this is bothering me too.

I think I have to keep it up-to-date, just like we keep Homebrew up-to-date because many people seem to be using it as part of the oh-my-zsh project (and there were similar bug reports there too).

**Comment by hnarayanan** [comment]
Ok team, we're getting closer: https://github.com/robbyrussell/oh-my-zsh/pull/6419

**Comment by hnarayanan** [comment]
An updated version of this project is now merged into `oh-my-zsh` and now it works when that’s installed!

**Comment by g-bon** [comment]
Great job!
