### ISSUE TITLE
A "pause" command that doesn't toggle play/pause

### ISSUE THREAD

**Issue by henrik242** [hnarayanan/shpotify#85]
I'd like a pause command that doesn't resume play if Spotify is already paused.  So maybe `spotify toggle` for play/pause toggle and `spotify pause` that always pauses?  Or maybe `spotify force-pause` so it doesn't interfere with the existing command?

**Comment by henrik242** [comment]
https://github.com/hnarayanan/shpotify/pull/66 solves this better than https://github.com/hnarayanan/shpotify/pull/86 IMHO

**Comment by hnarayanan** [comment]
Thank you!
