### ISSUE TITLE
spotify play list not working 

### ISSUE THREAD

**Issue by felipeauol** [hnarayanan/shpotify#89]
When searching for playlists, the API does not seem to find any playlists in Spotify wether user owned or not. For instance the command:

`spotify play list daily lift `

gives the following output:

`Searching playlists for: daily lift`
`No results when searching for daily lift`

**Comment by turbopope** [comment]
I'm having the same problem.

**Comment by hnarayanan** [comment]
Can someone who uses this feature please take a look?

**Comment by turbopope** [comment]
I'm looking into it, will submit a pull request later.

**Comment by turbopope** [comment]
Alright please check PR #90.

**Comment by hnarayanan** [comment]
This is now fixed thanks to @turbopope.

**Comment by dmofot** [comment]
If you want to create a new release, one of us can update the homebrew recipe.

**Comment by hnarayanan** [comment]
Not yet. I would like to fix the artist play thing too, then I'll make a release.

The thing I am really trying to get merged is https://github.com/robbyrussell/oh-my-zsh/pull/6419, which is blocking many zsh users (me included) from experiencing the canonical version of this script.

**Comment by hnarayanan** [comment]
@dmofot I've published a release (https://github.com/hnarayanan/shpotify/releases/tag/2.0.2) with recent fixes. :)

**Comment by dmofot** [comment]
Ok, Homebrew/homebrew-core/#21564 submitted and passed all checks.  Should be merged when they get around to it.

**Comment by dmofot** [comment]
Homebrew has merged the PR, should be all set.

**Comment by hnarayanan** [comment]
Thanks!
