### ISSUE TITLE
Shpotify picks unlikely choice

### ISSUE THREAD

**Issue by cubman3134** [hnarayanan/shpotify#98]
Instead of picking the first song in spotify's search or the first playlist/artist that comes up, shpotify plays an unrelated song. While this song does have certain keywords, this isn't how it generally acts.
<img width="1195" alt="dadrock" src="https://user-images.githubusercontent.com/16855685/38708774-c08972ae-3e85-11e8-9b5b-c8a1892e0ea9.png">

**Comment by hnarayanan** [comment]
I kinda see this, but it only seems to happen for really generic search terms. Generally if you add another word or something else to clarify, it seems to pick a reasonable result.
