### ISSUE TITLE
Return non-zero exit codes for invalid commands

### ISSUE THREAD

**Issue by dkniffin** [hnarayanan/shpotify#99]
To help with scripting, it'd be nice if shpotify returned a non-zero [exit code](collaboratively via the Slack messaging app.) gave when given invalid commands. Right now it returns an exit code of 0, with a Usage message.

Also, just FYI, this is for a project I'm working on called [Maestro](https://github.com/smashingboxes/maestro), a tool for controlling a Spotify player collaboratively via the Slack messaging app. I'm in the process of [rewriting it](https://github.com/smashingboxes/maestro/pull/6) to heavily rely on shpotify.

**Comment by hnarayanan** [comment]
Please contribute this if you know how to! 😊

**Comment by dkniffin** [comment]
I'll give it a shot!

**Comment by hnarayanan** [comment]
Thank you!
